server:
  port: 8080
spring:
  security:
    user:
      name: root
      password: e688f855-1859-49e2-b0e0-c31c510b724b
  mvc:
    format:
      date: yyyy-MM-dd
  datasource:
    url: jdbc:mysql://localhost:3306/liuqu
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  web:
    resources:
      static-locations: file:./image/
# Customised configurations
app:
  base-url: http://localhost:8080
